### PR TITLE
Mention the onboarding-eng Slack channel

### LINKED ISSUE #76: [RFC] New Hire Buddies
Insight: assigning someone as a mentor to a new hire that has been at Artsy for a while is good because they know lots of things, but it's bad because it's probably been a long time since they set certain things up. Another new hire is in a much better position to assist with these types of things because they just solved these problems!

For example, @pepopowitz just started and @starsirius asked if I'd like to be a mentor for him and I was happy to. I was able to help with a couple questions he had. Later he was asking about creating AWS and Jira accounts - something I haven't really thought much about.

@javamonn (for example) would be better suited to help getting someone setup on Jira since he's just done it and I actually don't even remember how I did it. Similarly, @ashleyjelks has just setup her AWS creds and ran into gotchas - she's in a much better position to help him out.

As a bonus, it feels good when you're new to a company to be asked to help with things. Makes one feel like they know stuff and are being helpful!

So, I wonder if there's a way to connect new hires so that they can learn from each other. It could be as informal as a slack group or formalized by assigning buddies in some way. Open to ideas here!

### PR DESCRIPTION
**Pull request by jonallured**
In an effort to connect new engineers, I've added a link the `onboarding-eng` Slack channel and nudge to have new hires :wave: at each other.

closes #76

### CODE REVIEW

**Comment by alloy** [comment]
Probably should also add this to the list of default channels for people in the `@developers` Slack group.

**Comment by jonallured** [comment]
@alloy good idea - where is this list?

**Comment by dleve123** [comment]
I believe we moved onboarding to artsy/potential (my example onboarding issue: https://github.com/artsy/potential/issues/211), so this should be updated there.

**Comment by jonallured** [comment]
@dleve123 oh hrm, very strange. Looks like the GitHub issue template is in README, but the actual onboarding issues are in potential? I wasn't aware of this change from onboarding in the open to moving it to potential. @orta any insight here?

**Comment by orta** [comment]
The issue gets posted in potential, but the templates haven't moved and IMO probably shouldn't. I moved the issues as they have personal-information in them into Potential but the templates don't (and then they also live with the rest of the general on boarding).

**Comment by orta** [comment]
The list is inside our slack group, I'll add it now

**Comment by orta** [comment]
OK, cool 👍

**Pull request merged**
