### PR TITLE
fix: change from forking to branching on main repo

### PR DESCRIPTION
**Pull request by admbtlr**
Following an [RFC](https://github.com/artsy/README/issues/309) and much discussion, we are now working in branches on the main repo instead of forks.

### CODE REVIEW

**Review by ashfurrow — COMMENTED** [review]
I mean, _I_ think this is a good idea, but should this be discussed in an RFC? Historically this has been a contentious topic at Artsy, but I could be missing recent discussions or context.

**Review by ashfurrow — APPROVED** [review]
Ahhhhh just saw the link, cool!!

**Comment by admbtlr** [comment]
Woah, that was quick! I thought this was already decided, after the RFC I linked to?

**Comment by admbtlr** [comment]
Is that the right format for the label? 🤔

**Comment by ashfurrow** [comment]
Hmm, let's see. #squashongreen

**Comment by ashfurrow** [comment]
Hmm that should have done it. I've deleted the label so Peril will re-create it: #squashongreen

**Comment by ashfurrow** [comment]
There we go, weird!

**Comment by ashfurrow** [comment]
Oh it might not squash if the label was added after the success event from CI, I'd just squash manually 👍

**Pull request merged**
