### PR TITLE
Rotation Docs Updates

### PR DESCRIPTION
**Pull request by chr-tatu**
**Changes Summary in sprint-rotation.md**
- Adding Rotation buddy responsibilities 
- Removing forced line wraps.
- Adding a suggestion to organize 1:1 with different team members
- Reducing the heading by 1, since the document only contained Header 2+.

### CODE REVIEW

**Review by joeyAghion — APPROVED** [review]
Last I checked, the line-wrapping was enforced by an automatic pre-commit hook. (However, I'm not a fan, so if you can get rid of that, or if I just have an old setup and can be ignored, that would be great.)

**Comment by chr-tatu** [comment]
> Last I checked, the line-wrapping was enforced by an automatic pre-commit hook. (However, I'm not a fan, so if you can get rid of that, or if I just have an old setup and can be ignored, that would be great.)

It makes sense to me, too. If someone wants a line wrap, it can be defined when viewing the file, not embedded in a file. I checked `.git/hooks` and there is no commit hook defined for this repo.

**Comment by lidimayra** [comment]
On the line wrapping topic, it's worth noting that a related discussion also happened here:  https://github.com/artsy/potential/issues/443

**Comment by joeyAghion** [comment]
The git hook (at least in my case) is also responsible for generating tables of contents (and maybe other things). See [the precommit command](https://github.com/artsy/README/blob/33ab04f1bb3ffe9a609ec4065f580b39adf787c9/package.json#L16).

I think this could merit some additional work (not related to this PR!), maybe just a `setup` script that sets up any necessary hooks, excluding the line-breaking.

**Comment by chr-tatu** [comment]
That's interesting. I didn't know about it. I'll add it to my todo list, @joeyAghion .

**Pull request merged**
