### PR TITLE
Update future-friday.md

### PR DESCRIPTION
**Pull request by patrinoua**
add link to jira board

### CODE REVIEW

**Review by olerichter00 — COMMENTED** [review]
I'm not sure whether we should use this Jira board across teams. What do you think?

**Comment by pvinis** [comment]
I didn't even know we had a board. in other teams we use jira labels or notion pages. others use nothing, just personal notes. maybe we should skip this link, and keep any FF info in team docs?

**Review by dblandin — COMMENTED** [review]
Since this is an experiment specifically within the Collector Experience team, I think we can either update the resource name to reflect that and merge or close the PR and wait to see if Jira boards become more broadly adopted for Future Friday project tracking.

**Comment by patrinoua** [comment]
@dblandin Thanks, I've updated the name of the link to reflect that

**Review by dblandin — APPROVED** [review]
LGTM 👍🏼

**Pull request merged**
