### PR TITLE
docs: guide on how to start renaming main branches in repos

### PR DESCRIPTION
**Pull request by kajatiger**
Writing a guide on what repos to start renaming the main branch to "main". Please feel free to add to the lists or comment if some repo is not a good candidate to start with because there might be a hidden complexity in it.

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Found a new file with underscores, this repo uses kebab-case for files: playbooks/rename_master_to_main.md
  </td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 464bd0c37535e955da27e1666a863ba2a407cc06
</p>

**Review by kajatiger — COMMENTED** [review]
Thanks @dblandin 🙂

**Comment by kajatiger** [comment]
Just found out that we in fact _do_ load our own artsy gems into the gemfile by referring to the `master` branch:
```ruby
  git: 'https://github.com/artsy/kinetic.git', branch: 'master'
```
and other examples. This needs to be considered as well!

**Comment by kajatiger** [comment]
Bildschirmfoto 2021-06-01 um 11 45 26

**Comment by kajatiger** [comment]
Bildschirmfoto 2021-06-01 um 11 46 43

**Comment by kajatiger** [comment]
Bildschirmfoto 2021-06-01 um 11 49 06

**Comment by kajatiger** [comment]
Bildschirmfoto 2021-06-01 um 11 49 19

**Comment by kajatiger** [comment]
Bildschirmfoto 2021-06-01 um 11 49 31

**Pull request merged**
