### PR TITLE
chore: rfc pr template

### PR DESCRIPTION
**Pull request by admbtlr**
Move the RFC templates from the `ISSUE_TEMPLATE` subdir to `PULL_REQUEST_TEMPLATE`.

### CODE REVIEW

**Comment by pvinis** [comment]
i see the removals, but where is the addition? 🤔

**Comment by admbtlr** [comment]
oops, sorry about that

**Comment by pvinis** [comment]
also, something to note.. github issues can have multiple templates. github pull requests cant. its one template for PRs and that's it.

Are we ok with the way these files are in that case? or do we wanna do a PR template that just points us to the RFC template to copy paste from? something else?

**Review by pvinis — APPROVED** [review]

**Comment by admbtlr** [comment]
looks like the idea of creating a PR from a link with `template` param won't work because PR links need to specify a branch, e.g. `/artsy/readme/compare/main...my-branch?quick_pull=1&template=issue_template.md` :(

**Comment by admbtlr** [comment]
I'm gonna move the templates to an innocuous subdir and reference them in the playbook

**Review by dblandin — APPROVED** [review]

**Comment by pvinis** [comment]
shall we merge this?

**Comment by admbtlr** [comment]
oh wow I'd forgotten about this

**Pull request merged**
