### PR TITLE
Adds to onboarding: general artsy/README callout, Engineer Workflow doc

### PR DESCRIPTION
**Pull request by mdole**
I found the Engineer Workflow doc very helpful for better understanding how we use GitHub and other services. Also noticed that there were a lot of links to artsy/README docs, but no general link to artsy/README itself - thought it worth calling out.

### CODE REVIEW

**Comment by orta** [comment]
I don't think the rendered markdown works for this change

**Comment by mdole** [comment]
Ooo you are correct, sorry about that. will fix and update

**Comment by mdole** [comment]
Merp 4 spaces instead of 2 T_T fixed, thanks @orta

**Comment by orta** [comment]
👍

**Pull request merged**
